// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class Answer
    {
        [Key]
        public int Id { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string AnswersText { get; set; }
        public bool IsCorrect { get; set; }
        public int? QuestionsId { get; set; }

        [ForeignKey("QuestionsId")]
        [InverseProperty("Answers")]
        public virtual Question Questions { get; set; }
    }
}