// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    [Index("TeachersId", Name = "IX_Courses_TeachersId")]
    public partial class Course
    {
        public Course()
        {
            Materials = new HashSet<Material>();
            Modules = new HashSet<Module>();
            StudentsCourses = new HashSet<StudentsCourse>();
            TeachersCourses = new HashSet<TeachersCourse>();
            Tests = new HashSet<Test>();
            Votes = new HashSet<Vote>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [StringLength(200)]
        public string Description { get; set; }
        public int Difficulty { get; set; }
        public int? TeachersId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedOn { get; set; }

        [ForeignKey("TeachersId")]
        [InverseProperty("Courses")]
        public virtual Teacher Teachers { get; set; }
        [InverseProperty("Courses")]
        public virtual ICollection<Material> Materials { get; set; }
        [InverseProperty("Courses")]
        public virtual ICollection<Module> Modules { get; set; }
        [InverseProperty("Courses")]
        public virtual ICollection<StudentsCourse> StudentsCourses { get; set; }
        [InverseProperty("Courses")]
        public virtual ICollection<TeachersCourse> TeachersCourses { get; set; }
        [InverseProperty("Courses")]
        public virtual ICollection<Test> Tests { get; set; }
        [InverseProperty("Courses")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}