// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class Question
    {
        public Question()
        {
            Answers = new HashSet<Answer>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "text")]
        public string QuestionText { get; set; }
        public int? TestsId { get; set; }

        [ForeignKey("TestsId")]
        [InverseProperty("Questions")]
        public virtual Test Tests { get; set; }
        [InverseProperty("Questions")]
        public virtual ICollection<Answer> Answers { get; set; }
    }
}