// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class Student
    {
        public Student()
        {
            StudentsCourses = new HashSet<StudentsCourse>();
            TestResults = new HashSet<TestResult>();
            Votes = new HashSet<Vote>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(100)]
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }
        public DateTime BirthDate { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedOn { get; set; }
        public Guid? UsersId { get; set; }

        [ForeignKey("UsersId")]
        [InverseProperty("Students")]
        public virtual User Users { get; set; }
        [InverseProperty("Students")]
        public virtual ICollection<StudentsCourse> StudentsCourses { get; set; }
        [InverseProperty("Students")]
        public virtual ICollection<TestResult> TestResults { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}