// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    [Index("CoursesId", Name = "IX_StudentsCourses_CoursesId")]
    public partial class StudentsCourse
    {
        [Key]
        public int StudentsId { get; set; }
        [Key]
        public int CoursesId { get; set; }

        [ForeignKey("CoursesId")]
        [InverseProperty("StudentsCourses")]
        public virtual Course Courses { get; set; }
        [ForeignKey("StudentsId")]
        [InverseProperty("StudentsCourses")]
        public virtual Student Students { get; set; }
    }
}