// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class Teacher
    {
        public Teacher()
        {
            Courses = new HashSet<Course>();
            TeachersCourses = new HashSet<TeachersCourse>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(100)]
        public string LastName { get; set; }
        public string Email { get; set; }
        public DateTime? HiredOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedOn { get; set; }
        public Guid? UsersId { get; set; }

        [ForeignKey("UsersId")]
        [InverseProperty("Teachers")]
        public virtual User Users { get; set; }
        [InverseProperty("Teachers")]
        public virtual ICollection<Course> Courses { get; set; }
        [InverseProperty("Teachers")]
        public virtual ICollection<TeachersCourse> TeachersCourses { get; set; }
    }
}