// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    [Index("CoursesId", Name = "IX_TeachersCourses_CoursesId")]
    public partial class TeachersCourse
    {
        [Key]
        public int TeachersId { get; set; }
        [Key]
        public int CoursesId { get; set; }

        [ForeignKey("CoursesId")]
        [InverseProperty("TeachersCourses")]
        public virtual Course Courses { get; set; }
        [ForeignKey("TeachersId")]
        [InverseProperty("TeachersCourses")]
        public virtual Teacher Teachers { get; set; }
    }
}