// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class TestResult
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(3, 2)")]
        public decimal? Result { get; set; }
        public int TestsId { get; set; }
        public int StudentsId { get; set; }

        [ForeignKey("StudentsId")]
        [InverseProperty("TestResults")]
        public virtual Student Students { get; set; }
        [ForeignKey("TestsId")]
        [InverseProperty("TestResults")]
        public virtual Test Tests { get; set; }
    }
}