// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class Test
    {
        public Test()
        {
            Questions = new HashSet<Question>();
            TestResults = new HashSet<TestResult>();
        }

        [Key]
        public int Id { get; set; }
        public DateTime? StardDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int Duration { get; set; }
        public int CoursesId { get; set; }

        [ForeignKey("CoursesId")]
        [InverseProperty("Tests")]
        public virtual Course Courses { get; set; }
        [InverseProperty("Tests")]
        public virtual ICollection<Question> Questions { get; set; }
        [InverseProperty("Tests")]
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}