// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    public partial class User 
    {
        public User()
        {
            Students = new HashSet<Student>();
            Teachers = new HashSet<Teacher>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [StringLength(100)]
        public string Email { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
        [Required]
        public string Password { get; set; }

        [InverseProperty("Users")]
        public virtual ICollection<Student> Students { get; set; }
        [InverseProperty("Users")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}