// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    [Keyless]
    public partial class UsersRole
    {
        public Guid UsersId { get; set; }
        public int RolesId { get; set; }

        [ForeignKey("RolesId")]
        public virtual Role Roles { get; set; }
        [ForeignKey("UsersId")]
        public virtual User Users { get; set; }
    }
}