// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccsess.Entities
{
    [Index("CoursesId", Name = "IX_Votes_CoursesId")]
    [Index("StudentId", Name = "IX_Votes_StudentId")]
    public partial class Vote
    {
        [Key]
        public int Id { get; set; }
        public bool IsLiked { get; set; }
        public int StudentId { get; set; }
        public int CoursesId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedOn { get; set; }

        [ForeignKey("CoursesId")]
        [InverseProperty("Votes")]
        public virtual Course Courses { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("Votes")]
        public virtual Student Student { get; set; }
    }
}